### ISSUE TITLE
The synchronous version of prettier breaks as soon as you have a non-serializable prettier config

### ISSUE THREAD

**Issue by AlexAegis** [remcohaszing/unified-prettier#1] opened 2023-07-16 17:48 UTC
Hey, it's me again from here: https://github.com/remcohaszing/remark-prettier/issues/2
I replaced remark-prettier with unified-pretter and unified-consistency, unfortunately when using both, my setup breaks since my prettier config has something serializable in it. 

I made a repro-repo for you https://github.com/AlexAegis/repro-remark-prettier and below there's a copy of the same readme that's in the repro:

# Prettier/Remark repro

## Steps to reproduce problem

- pnpm install
- Open with VS Code
- Have the `unifiedjs.vscode-remark` extension installed (This will report the
  error immediately)
- navigate to [packages/foo/readme.md](packages/foo/readme.md)
- you'll get an error:

  ```sh
    Error: Cannot serialize worker response
      at MessagePort.<anonymous> (file:///<REPO_ROOT>/node_modules/.pnpm/@prettier+sync@0.2.1_prettier@3.0.0/node_modules/@prettier/sync/worker.js:28:16)
  ```

## Core problem

`@pretter/sync` wants to `structuredClone` the prettier config
<https://github.com/prettier/prettier-synchronized/issues/4> which will fail if
you have something non-serializable like a function in it. Which you will have
if you have plugins imported directly in your config.

## Workarounds

- If you declare plugins as strings and let prettier load them, the issue goes
  away, but that's a pretty big limitation, and I want to redistribute my config
  as the `package/my-prettier-config` showcases it. I could just use a string,
  and it looks like that's okay for my usecase but if someone relies on configs
  that are loading prettier presets from 3pp packages, and they do load plugins
  directly like `package/my-prettier-config`, you wouldn't be able to do
  anything
- You can also remove either of the plugins from the `.remarkrc.js` file but
  that kinda defeats the point, since you just turn the prettier integration
  off.

> After trying out each workaround, reload vscode

## Possible solution

Remove `@prettier/sync` and use prettier directly, async.

**Comment by remcohaszing** [comment] 2023-07-17 09:32
Hi again! :wave: Thanks for trying this out immediately.

The problem is that unified compilers need to be synchronous. Prettier switched to async in version 3, so I can’t just use Prettier. Prettier provides `@prettier/sync` as a synchronous API leveraging worker threads, this is why indeed the config needs to be clonable using `structuredClone`. I reported https://github.com/unifiedjs/unified/issues/196 for Prettier 3 compatibility, but for me the use of `@prettier/sync` is sufficient.

So I acknowledge the issue, but there isn’t anything I can do to fix it. So I’m going to close this issue. I am open to practical solutions now and from future readers.

---

I see 2 workarounds that you could apply to your reusable configuration.

#### 1. Use peer dependencies

If you make the Prettier plugins `peerDependencies`, you can reference them by string. Both npm and pnpm install `peerDependencies` by default. Yarn 1 Doesn’t, but I recommend against using that as it’s pretty much dead.

#### 2. Resolve the paths

I haven’t use this myself, but I suspect you can use full paths to reference plugins in your reusable Prettier configurations.

I suspect the plugins you use are CJS, so you can use:

```js
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)

export default {
  plugins: [
    require.resolve('prettier-plugin-tailwindcss')
  ]
}
```

Alternatively, you can use [`import-meta-resolve`](https://github.com/wooorm/import-meta-resolve) (a ponyfill for the experimental `import.meta.resolve`)

```js
import { resolve } from 'import-meta-resolve'

export default {
  plugins: [
    resolve('prettier-plugin-tailwindcss', import.meta.url)
  ]
}
```

---

I hope this helps!

Perhaps the Prettier team would welcome a PR to [`@prettier/sync`](https://github.com/prettier/prettier-synchronized) to document these limitations.

Also, I really appreciate the level of detail you provided in the issue! :heart:

**Comment by JounQin** [comment] 2023-07-25 08:28
I believe this can be done with custom worker without depending on `@prettier/sync` like we do in [`eslint-plugin-prettier`](https://github.com/prettier/eslint-plugin-prettier/blob/master/worker.js)

What means doing all heavy jobs in the worker, and only return the result from it to bypass the limitations.

**Comment by remcohaszing** [comment] 2023-07-25 09:07
Ooh, you mean I move all of these lines into the worker?

https://github.com/remcohaszing/unified-prettier/blob/c1134475006835607ac99e9bb97f9783b58e44cf/index.ts#L31-L43

This way the only data that needs to be communicated with the worker thread is the original code and the formatted code, which are both just strings.

**Comment by remcohaszing** [comment] 2023-07-30 16:44
FWIW I have this working on my local machine. However, it doesn't work with `tsx`, so I need to convert from TypeScript to JavaScript.

I ran into https://github.com/microsoft/TypeScript/issues/55197 when generating types from JSDoc. This means I would have to write the type definitions manually.

I'm waiting for an answer to https://github.com/prettier/prettier-synchronized/issues/4#issuecomment-1649725277.

If it takes too long, I'll go with JavaScript and manually written type definitions.

**Comment by JounQin** [comment] 2023-07-31 05:42
> However, it doesn't work with tsx, so I need to convert from TypeScript to JavaScript.

What do you mean by it? Maybe you can try [`synckit`](https://github.com/un-ts/synckit) which supports TypeScript and `tsx` out of box?

**Closed as completed** 2023-08-01 13:03 UTC

**Comment by remcohaszing** [comment] 2023-08-01 13:04
See the description of 2f22eb8278e2393717d0344542b15f8425e594ed.

I prefer not to use `synckit`, because it pulls in a lot of dependencies for something that can be relatively small.

**Comment by AlexAegis** [comment] 2023-08-01 20:33
Thank you! This allowed me to use real plugin objects instead of strings in my [`prettier-config`](https://github.com/AlexAegis/js-tooling/blob/master/packages/prettier-config/src/index.ts) package. Which in turn allowed me to ignore another bug affecting resolving plugins by strings too: https://github.com/prettier/prettier/issues/15079 

I had to re-declare my plugins in every script as '--plugin prettier-plugin-svelte --plugin prettier-plugin-tailwindcss', and I no longer have to explicitly install the plugins next to prettier, but just let the config package depend on them. (The string-plugin-style-config didn't really like that with pnpm, idk if it had anything to do with 15079, but it doesn't matter now.)
